language: node_js

before_install:
  - mkdir travis-phantomjs
  - wget http://lively-web.org/users/robertkrahn/uploads/phantomjs-2.1.1-linux-x86_64.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs/phantomjs-2.1.1-linux-x86_64/bin:$PATH
  - phantomjs --version

node_js:
  - "5"

notifications:
  slack: cdglabs:fhJ0mRZkjMb0erIw3LetA9I2
